//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica_vesna
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTypeDirection
    {
        public int EventID { get; set; }
        public int EventTypeID { get; set; }
        public int DirectionID { get; set; }
    
        public virtual Directions Directions { get; set; }
        public virtual Events Events { get; set; }
        public virtual EventTypes EventTypes { get; set; }
    }
}
